### PR TITLE
Introduce real time status on endpoints

### PR DESCRIPTION
**Pull request by skelz0r**
Implement for both API Particulier (caf v1) and API Entreprise (INSEE Sirene)

More to come later

Closes https://linear.app/pole-api/issue/API-1174/integrer-le-statut-de-lapi-sur-la-page-du-catalogue

### CODE REVIEW

**Comment by skelz0r** [comment]
Screenshot 2023-09-28 at 12 24 07

**Comment by skelz0r** [comment]
https://linear.app/pole-api/issue/API-1174/integrer-le-statut-de-lapi-sur-la-page-du-catalogue

**Review by Samuelfaure — APPROVED** [review]
Super sympa cette feature

**Comment by DorineLam** [comment]
Super ! Merci @skelz0r

**Pull request merged**
